[colors.bright]
black = "#666666"
blue = "#81a2be"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#282a2e"
yellow = "#f0c674"

[colors.cursor]
cursor = "0x00ff00"
text = "0x000000"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#373b41"
yellow = "#e6c547"

[colors.primary]
background = "#242629"
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[27;5;49~"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;50~"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;51~"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;52~"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;53~"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;54~"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;55~"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;56~"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;57~"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;48~"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[window.padding]
x = 5
y = 0
